### ISSUE TITLE
Pergunta duplicada no FAQ da Landing Page sobre Automação de Lâmpadas

### ISSUE THREAD

**Issue by silash35** [optimusjr/website#17]
A pergunta “A automação de lâmpadas é compatível com diferentes tipos de lâmpadas, como LED, fluorescentes ou incandescentes?” na parte de perguntas frequentes da Landing Page sobre [automação de lâmpadas](https://optimusjr.com.br/lp/lights) está aparecendo duas vezes.

**Comment by coditalo** [comment]
feito
